name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master


jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6.0.3
      with:
        fetch-depth: 0
    - uses: astral-sh/setup-uv@v7
      with:
        python-version: "3.13"
    - run: make deps
    - run: make lint

  test:
    name: Test
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: lint

    strategy:
      fail-fast: false
      matrix:
        python: ["3.10", "3.11", "3.12", "3.13", "3.14"]
        pytest:
          - "pytest>=8.0,<8.1"
          - "pytest>=8.1,<8.2"
          - "pytest>=8.2,<8.3"
          - "pytest>=8.3,<8.4"
          - "pytest>=8.4,<8.5"
          - "pytest>=9.0,<9.1"
          - "pytest>=8,<9"   # latest 8.x
          - "pytest>=9,<10"  # latest 9.x

    env:
      UV_EXTRA_ARGS: --with "${{ matrix.pytest }}"

    steps:
    - uses: actions/checkout@v6.0.3
      with:
        fetch-depth: 0
    - uses: astral-sh/setup-uv@v7
      with:
        cache-suffix: py${{ matrix.python }}-job${{ strategy.job-index }}
    - run: echo ${{ matrix.python }} > .python-version
    - run: make deps
    - run: make test

  coverage:
    name: Coverage
    runs-on: ubuntu-latest
    needs: lint
    steps:
    - uses: actions/checkout@v6.0.3
      with:
        fetch-depth: 0
    - uses: astral-sh/setup-uv@v7
      with:
        python-version: "3.13"
    - run: make deps
    - run: make coverage
    - uses: codecov/codecov-action@v7
      with:
        files: coverage.xml
        fail_ci_if_error: false
        token: ${{ secrets.CODECOV_TOKEN }}
